"""Add LearningPack model

Revision ID: 8bc4f8e3e7e9
Revises: f022843c9b19
Create Date: 2025-12-04 16:16:32.053421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc4f8e3e7e9'
down_revision: Union[str, Sequence[str], None] = 'f022843c9b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_packs_id'), 'learning_packs', ['id'], unique=False)
    op.create_table('learning_pack_syllabus',
    sa.Column('learning_pack_id', sa.Integer(), nullable=True),
    sa.Column('syllabus_point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['learning_pack_id'], ['learning_packs.id'], ),
    sa.ForeignKeyConstraint(['syllabus_point_id'], ['syllabus_points.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_pack_syllabus')
    op.drop_index(op.f('ix_learning_packs_id'), table_name='learning_packs')
    op.drop_table('learning_packs')
    # ### end Alembic commands ###
