"""Add remaining models

Revision ID: be91760bc414
Revises: 8bc4f8e3e7e9
Create Date: 2025-12-04 16:17:49.730127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be91760bc414'
down_revision: Union[str, Sequence[str], None] = '8bc4f8e3e7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_exams_id'), 'mock_exams', ['id'], unique=False)
    op.create_index(op.f('ix_mock_exams_subject'), 'mock_exams', ['subject'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('question_number', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('exam_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('mock_exam_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mock_exam_id'], ['mock_exams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_attempts_id'), 'exam_attempts', ['id'], unique=False)
    op.create_table('learning_pack_resources',
    sa.Column('learning_pack_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['learning_pack_id'], ['learning_packs.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], )
    )
    op.create_table('mock_exam_questions',
    sa.Column('mock_exam_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mock_exam_id'], ['mock_exams.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], )
    )
    op.create_table('attempted_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_attempt_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('diagnosed_weakness', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exam_attempt_id'], ['exam_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempted_questions_id'), 'attempted_questions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempted_questions_id'), table_name='attempted_questions')
    op.drop_table('attempted_questions')
    op.drop_table('mock_exam_questions')
    op.drop_table('learning_pack_resources')
    op.drop_index(op.f('ix_exam_attempts_id'), table_name='exam_attempts')
    op.drop_table('exam_attempts')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_mock_exams_subject'), table_name='mock_exams')
    op.drop_index(op.f('ix_mock_exams_id'), table_name='mock_exams')
    op.drop_table('mock_exams')
    # ### end Alembic commands ###
